[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

## Edge Functions 설정: /view/* 요청은 봇일 경우 OG 메타 태그가 포함된 HTML을 반환
[edge_functions]
  directory = "edge-functions"

## 모든 경로에 대해 크롤러 접근 시 시스템 설정 기반 OG 메타 반환
[[edge_functions]]
  path = "/*"
  function = "promotion-og"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 