[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

# Edge Functions 설정: 모든 경로에서 크롤러 접근 시 시스템 설정 기반 OG 메타 반환
[edge_functions]
  directory = "edge-functions"

[[edge_functions]]
  path = "/*"
  function = "promotion-og"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 